datasets:
  - Lung
  - pancreas
  - Spleen
  - Tongue

seeds: [0, 1, 2, 3, 4]

training:
  epochs: 1000
  batch_size: 512
  lr: 1e-4
  device: cpu

classifier:
  hidden_dim: 128

encoder_models:
  - name: CAE
    class: ConcreteAutoencoderModel
    k_values: [1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 100, 200, 300, 400, 500]
    params:
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: IPCAE
    class: IndirectConcreteAutoencoderModel
    k_values: [1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 100, 200, 300, 400, 500]
    params:
      embedding_dim: 32
      initial_temperature: 1.0
      final_temperature: 0.01

gate_models:
  - name: STG
    class: StochasticGateModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    params:
      sigma: 1.0

  - name: GSG-Sigmoid
    class: GumbelSigmoidGateModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    params:
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: GSG-Softmax
    class: GumbelSoftmaxGateModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    params:
      embedding_dim: 16
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: HCG
    class: HardConcreteGateModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    params:
      min_max_scale: [-0.1, 1.1]
      temperature: 0.5

combined_models:
  - name: GSG-Softmax+CAE
    class: GumbelSoftmaxGateConcreteModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    k_values: [5, 10, 20, 30, 50]
    params:
      embedding_dim_gate: 16
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: GSG-Softmax+IPCAE
    class: GumbelSoftmaxGateIndirectConcreteModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    k_values: [5, 10, 20, 30, 50]
    params:
      embedding_dim_encoder: 32
      embedding_dim_gate: 16
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: STG+CAE
    class: StochasticGateConcreteModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    k_values: [5, 10, 20, 30, 50]
    params:
      sigma: 1.0
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: STG+IPCAE
    class: StochasticGateIndirectConcreteModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    k_values: [5, 10, 20, 30, 50]
    params:
      embedding_dim_encoder: 32
      sigma: 1.0
      initial_temperature: 1.0
      final_temperature: 0.01

  - name: HCG+CAE
    class: HardConcreteGateConcreteModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    k_values: [5, 10, 20, 30, 50]
    params:
      min_max_scale: [-0.1, 1.1]
      hcg_temperature: 0.5
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: HCG+IPCAE
    class: HardConcreteGateIndirectConcreteModel
    sparse_loss_weights: [0.1, 1, 10, 100]
    k_values: [5, 10, 20, 30, 50]
    params:
      embedding_dim_encoder: 32
      min_max_scale: [-0.1, 1.1]
      hcg_temperature: 0.5
      initial_temperature: 1.0
      final_temperature: 0.01

results_dir: exp/results/contrast
