task: regression
datasets:
  - SklearnReg

seeds: [0, 1, 2]

training:
  epochs: 300
  batch_size: 64
  lr: 2e-3
  device: cpu

head:
  hidden_dim: 128

k_default: 20

combined_models:
  - name: GSG-Softmax+IPCAE
    class: GumbelSoftmaxGateIndirectConcreteModel
    sparse_loss_weights: [1.0, 10.0]
    k_values: [20, 30]
    params:
      embedding_dim_encoder: 16
      embedding_dim_gate: 16
      initial_temperature: 10.0
      final_temperature: 0.01

  - name: HCG+IPCAE
    class: HardConcreteGateIndirectConcreteModel
    sparse_loss_weights: [1.0, 10.0]
    k_values: [20, 30]
    params:
      embedding_dim_encoder: 16
      initial_temperature: 10.0
      final_temperature: 0.01

results_dir: exp/results/reg_sw_ext
